branch-defaults:
  default:
    environment: flask-env-api-dev-v1
    group_suffix: null
environment-defaults:
  flask-api-ambient:
    branch: null
    repository: null
global:
  application_name: flask-api-v2
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.13
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
